// <auto-generated />
using System;
using API_BANKING_PAYMENT.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_BANKING_PAYMENT.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20250923100432_PendingChangesCheck")]
    partial class PendingChangesCheck
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Bank", b =>
                {
                    b.Property<long>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BankId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("BankId")
                        .HasName("bank_bankid_primary");

                    b.ToTable("Bank", (string)null);

                    b.HasData(
                        new
                        {
                            BankId = 1L,
                            Address = "Madam Cama Road, Mumbai, India",
                            BankName = "State Bank of India",
                            ContactEmail = "contact@sbi.co.in",
                            ContactPhone = "1800-123-456",
                            CreatedAt = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BankId = 2L,
                            Address = "Mumbai, Maharashtra, India",
                            BankName = "HDFC Bank",
                            ContactEmail = "contact@hdfcbank.com",
                            ContactPhone = "1800-234-567",
                            CreatedAt = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BankId = 3L,
                            Address = "Mumbai, Maharashtra, India",
                            BankName = "ICICI Bank",
                            ContactEmail = "contact@icicibank.com",
                            ContactPhone = "1800-345-678",
                            CreatedAt = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            BankId = 4L,
                            Address = "Mumbai, Maharashtra, India",
                            BankName = "Axis Bank",
                            ContactEmail = "contact@axisbank.com",
                            ContactPhone = "1800-456-789",
                            CreatedAt = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Beneficiary", b =>
                {
                    b.Property<long>("BeneficiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BeneficiaryId"));

                    b.Property<long>("AccountNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ifsccode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IFSCCode");

                    b.HasKey("BeneficiaryId")
                        .HasName("beneficiary_beneficiaryid_primary");

                    b.HasIndex("ClientId");

                    b.ToTable("Beneficiary", (string)null);
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Client", b =>
                {
                    b.Property<long>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("BankId")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RegisterationNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ClientId")
                        .HasName("client_clientid_primary");

                    b.HasIndex("BankId");

                    b.HasIndex(new[] { "RegisterationNumber" }, "client_registerationnumber_unique")
                        .IsUnique();

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Document", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocumentId"));

                    b.Property<long>("BankId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("DocType")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime");

                    b.Property<long>("UploadedBy")
                        .HasColumnType("bigint");

                    b.HasKey("DocumentId")
                        .HasName("document_documentid_primary");

                    b.HasIndex("UploadedBy");

                    b.ToTable("Document", (string)null);
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Employee", b =>
                {
                    b.Property<long>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EmployeeId"));

                    b.Property<long>("AccountNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ifsccode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("IFSCcode");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("SalaryAmount")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("EmployeeId")
                        .HasName("employee_employeeid_primary");

                    b.HasIndex("ClientId");

                    b.HasIndex(new[] { "Email" }, "employee_email_unique")
                        .IsUnique();

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<long?>("ApprovedBy")
                        .HasColumnType("bigint");

                    b.Property<long?>("BeneficiaryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Pending");

                    b.HasKey("PaymentId")
                        .HasName("payment_paymentid_primary");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("ClientId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Report", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportId"));

                    b.Property<string>("FileUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime");

                    b.Property<long>("GeneratedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ReportId")
                        .HasName("report_reportid_primary");

                    b.HasIndex("GeneratedBy");

                    b.ToTable("Report", (string)null);
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.SalaryDisbursement", b =>
                {
                    b.Property<long>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SalaryId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DisbursementDate")
                        .HasColumnType("datetime");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Pending");

                    b.HasKey("SalaryId")
                        .HasName("salarydisbursement_salaryid_primary");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryDisbursement", (string)null);
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<long?>("BankId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId")
                        .HasName("user_userid_primary");

                    b.HasIndex("BankId");

                    b.HasIndex("ClientId");

                    b.HasIndex(new[] { "Email" }, "user_email_unique")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "superAdmin@gmail.com",
                            FullName = "SuperAdmin",
                            PasswordHash = "$2a$11$jHouR8b8dzPXF6gipSngJungngAfK2s./8WMSWUpor0Zs1h9iDTnS",
                            Role = "SuperAdmin",
                            UserName = "superadmin"
                        });
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Beneficiary", b =>
                {
                    b.HasOne("API_BANKING_PAYMENT.Models.Entities.Client", "Client")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("beneficiary_clientid_foreign");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Client", b =>
                {
                    b.HasOne("API_BANKING_PAYMENT.Models.Entities.Bank", "Bank")
                        .WithMany("Clients")
                        .HasForeignKey("BankId")
                        .IsRequired()
                        .HasConstraintName("client_bankid_foreign");

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Document", b =>
                {
                    b.HasOne("API_BANKING_PAYMENT.Models.Entities.User", "UploadedByNavigation")
                        .WithMany("Documents")
                        .HasForeignKey("UploadedBy")
                        .IsRequired()
                        .HasConstraintName("document_uploadedby_foreign");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Employee", b =>
                {
                    b.HasOne("API_BANKING_PAYMENT.Models.Entities.Client", "Client")
                        .WithMany("Employees")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("employee_clientid_foreign");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Payment", b =>
                {
                    b.HasOne("API_BANKING_PAYMENT.Models.Entities.User", "ApprovedByNavigation")
                        .WithMany("Payments")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("payment_approvedby_foreign");

                    b.HasOne("API_BANKING_PAYMENT.Models.Entities.Beneficiary", "Beneficiary")
                        .WithMany("Payments")
                        .HasForeignKey("BeneficiaryId")
                        .HasConstraintName("payment_beneficiaryid_foreign");

                    b.HasOne("API_BANKING_PAYMENT.Models.Entities.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("payment_clientid_foreign");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Beneficiary");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Report", b =>
                {
                    b.HasOne("API_BANKING_PAYMENT.Models.Entities.User", "GeneratedByNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("GeneratedBy")
                        .IsRequired()
                        .HasConstraintName("report_generatedby_foreign");

                    b.Navigation("GeneratedByNavigation");
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.SalaryDisbursement", b =>
                {
                    b.HasOne("API_BANKING_PAYMENT.Models.Entities.Client", "Client")
                        .WithMany("SalaryDisbursements")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("salarydisbursement_clientid_foreign");

                    b.HasOne("API_BANKING_PAYMENT.Models.Entities.Employee", "Employee")
                        .WithMany("SalaryDisbursements")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("salarydisbursement_employeeid_foreign");

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.User", b =>
                {
                    b.HasOne("API_BANKING_PAYMENT.Models.Entities.Bank", "Bank")
                        .WithMany("Users")
                        .HasForeignKey("BankId")
                        .HasConstraintName("user_bankid_foreign");

                    b.HasOne("API_BANKING_PAYMENT.Models.Entities.Client", "Client")
                        .WithMany("Users")
                        .HasForeignKey("ClientId")
                        .HasConstraintName("user_clientid_foreign");

                    b.Navigation("Bank");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Bank", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Beneficiary", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Client", b =>
                {
                    b.Navigation("Beneficiaries");

                    b.Navigation("Employees");

                    b.Navigation("Payments");

                    b.Navigation("SalaryDisbursements");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.Employee", b =>
                {
                    b.Navigation("SalaryDisbursements");
                });

            modelBuilder.Entity("API_BANKING_PAYMENT.Models.Entities.User", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Payments");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
